# This is a basic workflow to help you get started with Actions

name: sample-workflow-1

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "sample"
  sample:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      MONGOCLI_DEB: "https://github.com/mongodb/mongocli/releases/download/v1.4.0/mongocli_1.4.0_linux_x86_64.deb"
      MCLI_PUBLIC_API_KEY: ${{ secrets.MCLI_PUBLIC_API_KEY }}
      MCLI_PRIVATE_API_KEY: ${{ secrets.MCLI_PRIVATE_API_KEY }} 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Install mongocli
      run:  curl -OL "${MONGOCLI_DEB}" | dpkg -i
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
